import requests
import json

def consultar_api(url, token):
    headers = {
        'Authorization': token
    }

    response = requests.get(url, headers=headers)

    if response.status_code == 200:
        data = response.json()
        return data
    else:
        print("Error al consultar la API:")
        print("Código de estado:", response.status_code)
        return None

# URL de la API y token proporcionados
url = "https://api.perueduca.pe/pe-educational-materials/v1/related/educational-materials:values/url/yo-tambien-me-cuido-aprendo-en-casa-2021-tv-inicial-26-de-abril"
token = "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJuTzkxQXUyTkU4NXFua3h2N3ZLYjNlNUlNVFh1SWF2ZHQ2S1dPVGE0ZGlNIn0.eyJleHAiOjE3MTQ3NjgyNzUsImlhdCI6MTcxNDc2Nzk3NSwianRpIjoiMGFiMjJiMDYtYmRkOS00NTdjLWE2MmQtN2QxNTVmY2I4M2I3IiwiaXNzIjoiaHR0cHM6Ly9pZGVudGlkYWQubWluZWR1LmdvYi5wZS9yZWFsbXMvcGUtd2ViIiwiYXVkIjpbInBlLndlYi1hcHAucG9ydGFsLWxlZ2FjeSIsInBlLndlYi1zZXJ2aWNlcy5jb21tZW50cyIsInBlLndlYi1zZXJ2aWNlcy51c2VyLmFjY291bnRzIiwicGUud2ViLXNlcnZpY2VzLnNlYXJjaCIsInBlLndlYi1hcHAucG9ydGFsIiwicGUud2ViLXNlcnZpY2VzLmVkdWNhdGlvbmFsLW1hdGVyaWFscyIsInBlLndlYi1zZXJ2aWNlcy5tZXRhZGF0YSIsInBlLndlYi1zZXJ2aWNlcy5yYXRpbmdzIiwicGUud2ViLXNlcnZpY2VzLnN0cmVhbWluZ3MiLCJwZS53ZWItc2VydmljZXMuYW5hbHl0aWNzIiwicGUud2ViLXNlcnZpY2VzLndlYi1jb250ZW50cyJdLCJzdWIiOiI0YTAxZDlhMS00YmE2LTQ3MGYtYTkzMS1hNmEyZDU3MGUyMjEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJwZS5zZXJ2aWNlLWFjY291bnQub24tZ3Vlc3QiLCJyZXNvdXJjZV9hY2Nlc3MiOnsicGUud2ViLWFwcC5wb3J0YWwtbGVnYWN5Ijp7InJvbGVzIjpbInByb2ZpbGU6Z3Vlc3QiXX0sInBlLndlYi1zZXJ2aWNlcy5jb21tZW50cyI6eyJyb2xlcyI6WyJjb21tZW50czp2YWx1ZXM6cmVhZCJdfSwicGUud2ViLXNlcnZpY2VzLnVzZXIuYWNjb3VudHMiOnsicm9sZXMiOlsidXNlci1hY2NvdW50czpzb2NpYWwtbWVkaWE6cmVhZCJdfSwicGUud2ViLXNlcnZpY2VzLnNlYXJjaCI6eyJyb2xlcyI6WyJzZWFyY2g6aW5kZXg6cmVhZCJdfSwicGUud2ViLWFwcC5wb3J0YWwiOnsicm9sZXMiOlsicHJvZmlsZTpndWVzdCJdfSwicGUud2ViLXNlcnZpY2VzLmVkdWNhdGlvbmFsLW1hdGVyaWFscyI6eyJyb2xlcyI6WyJlZHVjYXRpb25hbC1tYXRlcmlhbHM6dmFsdWVzOnJlYWQiXX0sInBlLndlYi1zZXJ2aWNlcy5tZXRhZGF0YSI6eyJyb2xlcyI6WyJtZXRhZGF0YTpuYW1lOnJlYWQiXX0sInBlLndlYi1zZXJ2aWNlcy5yYXRpbmdzIjp7InJvbGVzIjpbInJhdGluZ3M6dmFsdWVzOnJlYWQiXX0sInBlLndlYi1zZXJ2aWNlcy5zdHJlYW1pbmdzIjp7InJvbGVzIjpbInN0cmVhbWluZ3M6cmVhZCJdfSwicGUud2ViLXNlcnZpY2VzLmFuYWx5dGljcyI6eyJyb2xlcyI6WyJhbmFseXRpY3M6dmlld3M6cmVhZCIsImFuYWx5dGljczp2aWV3czp3cml0ZSJdfSwicGUud2ViLXNlcnZpY2VzLndlYi1jb250ZW50cyI6eyJyb2xlcyI6WyJ3ZWItY29udGVudHM6Y2F0ZWdvcmllczpyZWFkIiwid2ViLWNvbnRlbnRzOnJlc291cmNlczpyZWFkIl19fSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJjbGllbnRIb3N0IjoiMTAuMjU1LjI1NS40MiIsImNsaWVudElkIjoicGUuc2VydmljZS1hY2NvdW50Lm9uLWd1ZXN0IiwicHJlZmVycmVkX3VzZXJuYW1lIjoic2VydmljZS1hY2NvdW50LXBlLnNlcnZpY2UtYWNjb3VudC5vbi1ndWVzdCIsImNsaWVudEFkZHJlc3MiOiIxMC4yNTUuMjU1LjQyIn0.Hw428CH81o4rl6b3BqxlSq_z5Xn-SW8dsfK0P43xoDsEIi_UzelyCRu--J-iPL7wdmmxdu2rL_YBbLWN3ODsRaUv6qVSur-zyDU1e2z3040Wai2pkkQRMtvnpAFPKuXSweyOEHkYc5R-OY55cqVdOjLFA299rd04M5mx42lpgu8jmWWKU5QiajcJm71jK4NT-KQ1zYg9oOcOo6_5zaOMVVmJlCnomAc7bGyDZR_4_GTwem1N734S6TYNBj40rLPAT0G_cIN56c3hn2tREbVEj75SQvoym4qr6Sf4dTzqAGBvTJA8yachdQ5k4_0ClODqVK7l1Ae3wDoReeDmOHp8Bw"

# Usar la función para obtener los datos de la API
datos_api = consultar_api(url, token)

# Guardar los datos obtenidos en un archivo JSON si no son None
if datos_api is not None:
    with open('datos_api.json', 'w', encoding='utf-8') as file:
        json.dump(datos_api, file, ensure_ascii=False, indent=4)
else:
    print("No se pudo obtener datos válidos de la API.")
